# To execute this docker-compose yml file use `docker-compose -f <file_name> up`
# Add the `-d` flag at the end for detached execution
version: '2'
services:
  chrome:
    image: selenium/node-chrome:latest
    volumes:
      - /dev/shm1:/dev/shm1
    depends_on:
      - hub
    environment:
      HUB_HOST: hub

  firefox:
    image: selenium/node-firefox:latest
    volumes:
      - /dev/shm1:/dev/shm2
    depends_on:
      - hub
    environment:
      HUB_HOST: hub

  opera:
    image: selenium/node-opera:latest
    volumes:
      - /dev/shm1:/dev/shm3
    depends_on:
      - hub
    environment:
      HUB_HOST: hub

  hub:
    image: selenium/hub:latest
    ports:
      - "4444:4444"